-- MySQL Script generated by MySQL Workbench
-- Tue May  5 00:46:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gastrosoft_course
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gastrosoft_course
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gastrosoft_course` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `gastrosoft_course` ;

-- -----------------------------------------------------
-- Table `gastrosoft_course`.`employee_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`employee_role` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `uq_role_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_role_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`employee` (
  `employee_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_id` INT UNSIGNED NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(100) NOT NULL,
  `middle_name` VARCHAR(100) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `hire_date` DATE NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`employee_id`),
  INDEX `idx_employee_role` (`role_id` ASC) VISIBLE,
  INDEX `idx_employee_name` (`last_name` ASC, `first_name` ASC) VISIBLE,
  CONSTRAINT `fk_employee_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `gastrosoft_course`.`employee_role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`app_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`app_user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employee_id` INT UNSIGNED NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `uq_app_user_employee` (`employee_id` ASC) VISIBLE,
  UNIQUE INDEX `uq_app_user_login` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_app_user_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `gastrosoft_course`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`payment_method` (
  `payment_method_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`payment_method_id`),
  UNIQUE INDEX `uq_payment_method_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_payment_method_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`guest` (
  `guest_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`guest_id`),
  INDEX `idx_guest_name` (`full_name` ASC) VISIBLE,
  INDEX `idx_guest_phone` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`reservation_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`reservation_status` (
  `reservation_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`reservation_status_id`),
  UNIQUE INDEX `uq_reservation_status_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_reservation_status_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`restaurant_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`restaurant_table` (
  `table_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `seats_count` TINYINT UNSIGNED NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`table_id`),
  UNIQUE INDEX `uq_restaurant_table_code` (`code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`reservation` (
  `reservation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guest_id` INT UNSIGNED NOT NULL,
  `table_id` INT UNSIGNED NULL DEFAULT NULL,
  `reservation_status_id` INT UNSIGNED NOT NULL,
  `reserved_from` DATETIME NOT NULL,
  `reserved_to` DATETIME NOT NULL,
  `guest_count` TINYINT UNSIGNED NOT NULL,
  `created_by_user_id` INT UNSIGNED NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reservation_id`),
  INDEX `idx_reservation_guest` (`guest_id` ASC) VISIBLE,
  INDEX `idx_reservation_table` (`table_id` ASC) VISIBLE,
  INDEX `idx_reservation_status` (`reservation_status_id` ASC) VISIBLE,
  INDEX `idx_reservation_datetime` (`reserved_from` ASC, `reserved_to` ASC) VISIBLE,
  INDEX `idx_reservation_created_by` (`created_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_created_by`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `gastrosoft_course`.`app_user` (`user_id`),
  CONSTRAINT `fk_reservation_guest`
    FOREIGN KEY (`guest_id`)
    REFERENCES `gastrosoft_course`.`guest` (`guest_id`),
  CONSTRAINT `fk_reservation_status`
    FOREIGN KEY (`reservation_status_id`)
    REFERENCES `gastrosoft_course`.`reservation_status` (`reservation_status_id`),
  CONSTRAINT `fk_reservation_table`
    FOREIGN KEY (`table_id`)
    REFERENCES `gastrosoft_course`.`restaurant_table` (`table_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`order_status` (
  `order_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`order_status_id`),
  UNIQUE INDEX `uq_order_status_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_order_status_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`customer_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`customer_order` (
  `order_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `table_id` INT UNSIGNED NULL DEFAULT NULL,
  `reservation_id` INT UNSIGNED NULL DEFAULT NULL,
  `order_status_id` INT UNSIGNED NOT NULL,
  `created_by_user_id` INT UNSIGNED NOT NULL,
  `payment_method_id` INT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `closed_at` DATETIME NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `idx_customer_order_table` (`table_id` ASC) VISIBLE,
  INDEX `idx_customer_order_reservation` (`reservation_id` ASC) VISIBLE,
  INDEX `idx_customer_order_status` (`order_status_id` ASC) VISIBLE,
  INDEX `idx_customer_order_created_by` (`created_by_user_id` ASC) VISIBLE,
  INDEX `idx_customer_order_payment_method` (`payment_method_id` ASC) VISIBLE,
  INDEX `idx_customer_order_created_at` (`created_at` ASC) VISIBLE,
  CONSTRAINT `fk_customer_order_created_by`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `gastrosoft_course`.`app_user` (`user_id`),
  CONSTRAINT `fk_customer_order_payment_method`
    FOREIGN KEY (`payment_method_id`)
    REFERENCES `gastrosoft_course`.`payment_method` (`payment_method_id`),
  CONSTRAINT `fk_customer_order_reservation`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `gastrosoft_course`.`reservation` (`reservation_id`),
  CONSTRAINT `fk_customer_order_status`
    FOREIGN KEY (`order_status_id`)
    REFERENCES `gastrosoft_course`.`order_status` (`order_status_id`),
  CONSTRAINT `fk_customer_order_table`
    FOREIGN KEY (`table_id`)
    REFERENCES `gastrosoft_course`.`restaurant_table` (`table_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`menu_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`menu_category` (
  `category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `sort_order` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `uq_menu_category_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`dish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`dish` (
  `dish_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `category_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `base_price` DECIMAL(10,2) NOT NULL,
  `prep_time_minutes` INT UNSIGNED NULL DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  `photo_url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`dish_id`),
  UNIQUE INDEX `uq_dish_name` (`name` ASC) VISIBLE,
  INDEX `idx_dish_category` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_dish_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `gastrosoft_course`.`menu_category` (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`modifier_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`modifier_group` (
  `modifier_group_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`modifier_group_id`),
  UNIQUE INDEX `uq_modifier_group_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`dish_modifier_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`dish_modifier_group` (
  `dish_id` INT UNSIGNED NOT NULL,
  `modifier_group_id` INT UNSIGNED NOT NULL,
  `min_select_count` TINYINT UNSIGNED NOT NULL DEFAULT '0',
  `max_select_count` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `sort_order` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`dish_id`, `modifier_group_id`),
  INDEX `idx_dish_modifier_group_group` (`modifier_group_id` ASC) VISIBLE,
  CONSTRAINT `fk_dish_modifier_group_dish`
    FOREIGN KEY (`dish_id`)
    REFERENCES `gastrosoft_course`.`dish` (`dish_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_dish_modifier_group_group`
    FOREIGN KEY (`modifier_group_id`)
    REFERENCES `gastrosoft_course`.`modifier_group` (`modifier_group_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`shift_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`shift_type` (
  `shift_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `default_start_time` TIME NULL DEFAULT NULL,
  `default_end_time` TIME NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`shift_type_id`),
  UNIQUE INDEX `uq_shift_type_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_shift_type_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`employee_shift_preference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`employee_shift_preference` (
  `employee_id` INT UNSIGNED NOT NULL,
  `shift_type_id` INT UNSIGNED NOT NULL,
  `preference_level` TINYINT UNSIGNED NOT NULL DEFAULT '3',
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`, `shift_type_id`),
  INDEX `idx_employee_shift_preference_type` (`shift_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_shift_preference_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `gastrosoft_course`.`employee` (`employee_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_employee_shift_preference_type`
    FOREIGN KEY (`shift_type_id`)
    REFERENCES `gastrosoft_course`.`shift_type` (`shift_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`skill` (
  `skill_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`skill_id`),
  UNIQUE INDEX `uq_skill_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`employee_skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`employee_skill` (
  `employee_id` INT UNSIGNED NOT NULL,
  `skill_id` INT UNSIGNED NOT NULL,
  `skill_level` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`employee_id`, `skill_id`),
  INDEX `idx_employee_skill_skill` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `fk_employee_skill_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `gastrosoft_course`.`employee` (`employee_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_employee_skill_skill`
    FOREIGN KEY (`skill_id`)
    REFERENCES `gastrosoft_course`.`skill` (`skill_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`measurement_unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`measurement_unit` (
  `measurement_unit_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(20) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`measurement_unit_id`),
  UNIQUE INDEX `uq_measurement_unit_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_measurement_unit_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`ingredient` (
  `ingredient_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `measurement_unit_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `cost_per_unit` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `critical_level` DECIMAL(10,3) NOT NULL DEFAULT '0.000',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ingredient_id`),
  UNIQUE INDEX `uq_ingredient_name` (`name` ASC) VISIBLE,
  INDEX `idx_ingredient_unit` (`measurement_unit_id` ASC) VISIBLE,
  CONSTRAINT `fk_ingredient_unit`
    FOREIGN KEY (`measurement_unit_id`)
    REFERENCES `gastrosoft_course`.`measurement_unit` (`measurement_unit_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`order_item_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`order_item_status` (
  `order_item_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`order_item_status_id`),
  UNIQUE INDEX `uq_order_item_status_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_order_item_status_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`order_item` (
  `order_item_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_id` INT UNSIGNED NOT NULL,
  `dish_id` INT UNSIGNED NOT NULL,
  `order_item_status_id` INT UNSIGNED NOT NULL,
  `quantity` INT UNSIGNED NOT NULL DEFAULT '1',
  `unit_price` DECIMAL(10,2) NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `idx_order_item_order` (`order_id` ASC) VISIBLE,
  INDEX `idx_order_item_dish` (`dish_id` ASC) VISIBLE,
  INDEX `idx_order_item_status` (`order_item_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_dish`
    FOREIGN KEY (`dish_id`)
    REFERENCES `gastrosoft_course`.`dish` (`dish_id`),
  CONSTRAINT `fk_order_item_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `gastrosoft_course`.`customer_order` (`order_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_order_item_status`
    FOREIGN KEY (`order_item_status_id`)
    REFERENCES `gastrosoft_course`.`order_item_status` (`order_item_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`stock_operation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`stock_operation_type` (
  `stock_operation_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `operation_sign` SMALLINT NOT NULL,
  PRIMARY KEY (`stock_operation_type_id`),
  UNIQUE INDEX `uq_stock_operation_type_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_stock_operation_type_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`inventory_operation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`inventory_operation` (
  `operation_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ingredient_id` INT UNSIGNED NOT NULL,
  `stock_operation_type_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  `operation_datetime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `performed_by_user_id` INT UNSIGNED NULL DEFAULT NULL,
  `related_order_item_id` INT UNSIGNED NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`operation_id`),
  INDEX `idx_inventory_operation_ingredient` (`ingredient_id` ASC) VISIBLE,
  INDEX `idx_inventory_operation_type` (`stock_operation_type_id` ASC) VISIBLE,
  INDEX `idx_inventory_operation_datetime` (`operation_datetime` ASC) VISIBLE,
  INDEX `idx_inventory_operation_user` (`performed_by_user_id` ASC) VISIBLE,
  INDEX `idx_inventory_operation_order_item` (`related_order_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_operation_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `gastrosoft_course`.`ingredient` (`ingredient_id`),
  CONSTRAINT `fk_inventory_operation_order_item`
    FOREIGN KEY (`related_order_item_id`)
    REFERENCES `gastrosoft_course`.`order_item` (`order_item_id`),
  CONSTRAINT `fk_inventory_operation_type`
    FOREIGN KEY (`stock_operation_type_id`)
    REFERENCES `gastrosoft_course`.`stock_operation_type` (`stock_operation_type_id`),
  CONSTRAINT `fk_inventory_operation_user`
    FOREIGN KEY (`performed_by_user_id`)
    REFERENCES `gastrosoft_course`.`app_user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`modifier_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`modifier_option` (
  `modifier_option_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modifier_group_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `extra_price` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  `is_active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`modifier_option_id`),
  UNIQUE INDEX `uq_modifier_option_group_name` (`modifier_group_id` ASC, `name` ASC) VISIBLE,
  CONSTRAINT `fk_modifier_option_group`
    FOREIGN KEY (`modifier_group_id`)
    REFERENCES `gastrosoft_course`.`modifier_group` (`modifier_group_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`order_item_modifier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`order_item_modifier` (
  `order_item_id` INT UNSIGNED NOT NULL,
  `modifier_option_id` INT UNSIGNED NOT NULL,
  `extra_charge` DECIMAL(10,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`order_item_id`, `modifier_option_id`),
  INDEX `idx_order_item_modifier_option` (`modifier_option_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_modifier_option`
    FOREIGN KEY (`modifier_option_id`)
    REFERENCES `gastrosoft_course`.`modifier_option` (`modifier_option_id`),
  CONSTRAINT `fk_order_item_modifier_order_item`
    FOREIGN KEY (`order_item_id`)
    REFERENCES `gastrosoft_course`.`order_item` (`order_item_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`recipe_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`recipe_item` (
  `dish_id` INT UNSIGNED NOT NULL,
  `ingredient_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(10,3) NOT NULL,
  PRIMARY KEY (`dish_id`, `ingredient_id`),
  INDEX `idx_recipe_item_ingredient` (`ingredient_id` ASC) VISIBLE,
  CONSTRAINT `fk_recipe_item_dish`
    FOREIGN KEY (`dish_id`)
    REFERENCES `gastrosoft_course`.`dish` (`dish_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_recipe_item_ingredient`
    FOREIGN KEY (`ingredient_id`)
    REFERENCES `gastrosoft_course`.`ingredient` (`ingredient_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`shift_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`shift_status` (
  `shift_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`shift_status_id`),
  UNIQUE INDEX `uq_shift_status_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_shift_status_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`work_shift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`work_shift` (
  `shift_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shift_type_id` INT UNSIGNED NOT NULL,
  `shift_status_id` INT UNSIGNED NOT NULL,
  `planned_start` DATETIME NOT NULL,
  `planned_end` DATETIME NOT NULL,
  `created_by_user_id` INT UNSIGNED NOT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`shift_id`),
  INDEX `idx_work_shift_type` (`shift_type_id` ASC) VISIBLE,
  INDEX `idx_work_shift_status` (`shift_status_id` ASC) VISIBLE,
  INDEX `idx_work_shift_period` (`planned_start` ASC, `planned_end` ASC) VISIBLE,
  INDEX `idx_work_shift_created_by` (`created_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_shift_created_by`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `gastrosoft_course`.`app_user` (`user_id`),
  CONSTRAINT `fk_work_shift_status`
    FOREIGN KEY (`shift_status_id`)
    REFERENCES `gastrosoft_course`.`shift_status` (`shift_status_id`),
  CONSTRAINT `fk_work_shift_type`
    FOREIGN KEY (`shift_type_id`)
    REFERENCES `gastrosoft_course`.`shift_type` (`shift_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`shift_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`shift_assignment` (
  `assignment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `shift_id` INT UNSIGNED NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `assignment_role_id` INT UNSIGNED NOT NULL,
  `check_in_time` DATETIME NULL DEFAULT NULL,
  `check_out_time` DATETIME NULL DEFAULT NULL,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`assignment_id`),
  UNIQUE INDEX `uq_shift_assignment` (`shift_id` ASC, `employee_id` ASC) VISIBLE,
  INDEX `idx_shift_assignment_employee` (`employee_id` ASC) VISIBLE,
  INDEX `idx_shift_assignment_role` (`assignment_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_shift_assignment_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `gastrosoft_course`.`employee` (`employee_id`),
  CONSTRAINT `fk_shift_assignment_role`
    FOREIGN KEY (`assignment_role_id`)
    REFERENCES `gastrosoft_course`.`employee_role` (`role_id`),
  CONSTRAINT `fk_shift_assignment_shift`
    FOREIGN KEY (`shift_id`)
    REFERENCES `gastrosoft_course`.`work_shift` (`shift_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`swap_request_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`swap_request_status` (
  `swap_request_status_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(30) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`swap_request_status_id`),
  UNIQUE INDEX `uq_swap_request_status_code` (`code` ASC) VISIBLE,
  UNIQUE INDEX `uq_swap_request_status_name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`shift_swap_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`shift_swap_request` (
  `swap_request_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `assignment_id` INT UNSIGNED NOT NULL,
  `requested_employee_id` INT UNSIGNED NULL DEFAULT NULL,
  `swap_request_status_id` INT UNSIGNED NOT NULL,
  `requested_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `processed_at` DATETIME NULL DEFAULT NULL,
  `decided_by_user_id` INT UNSIGNED NULL DEFAULT NULL,
  `reason` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`swap_request_id`),
  INDEX `idx_shift_swap_request_assignment` (`assignment_id` ASC) VISIBLE,
  INDEX `idx_shift_swap_request_employee` (`requested_employee_id` ASC) VISIBLE,
  INDEX `idx_shift_swap_request_status` (`swap_request_status_id` ASC) VISIBLE,
  INDEX `idx_shift_swap_request_decided_by` (`decided_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_shift_swap_request_assignment`
    FOREIGN KEY (`assignment_id`)
    REFERENCES `gastrosoft_course`.`shift_assignment` (`assignment_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_shift_swap_request_decided_by`
    FOREIGN KEY (`decided_by_user_id`)
    REFERENCES `gastrosoft_course`.`app_user` (`user_id`),
  CONSTRAINT `fk_shift_swap_request_employee`
    FOREIGN KEY (`requested_employee_id`)
    REFERENCES `gastrosoft_course`.`employee` (`employee_id`),
  CONSTRAINT `fk_shift_swap_request_status`
    FOREIGN KEY (`swap_request_status_id`)
    REFERENCES `gastrosoft_course`.`swap_request_status` (`swap_request_status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`workload_forecast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`workload_forecast` (
  `forecast_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `forecast_start` DATETIME NOT NULL,
  `forecast_end` DATETIME NOT NULL,
  `expected_guests` INT UNSIGNED NOT NULL,
  `expected_orders` INT UNSIGNED NOT NULL,
  `hall_load_percent` DECIMAL(5,2) NOT NULL,
  `kitchen_load_percent` DECIMAL(5,2) NOT NULL,
  `created_by_user_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `note` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`forecast_id`),
  INDEX `idx_workload_forecast_period` (`forecast_start` ASC, `forecast_end` ASC) VISIBLE,
  INDEX `idx_workload_forecast_created_by` (`created_by_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_workload_forecast_created_by`
    FOREIGN KEY (`created_by_user_id`)
    REFERENCES `gastrosoft_course`.`app_user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `gastrosoft_course`.`staffing_requirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gastrosoft_course`.`staffing_requirement` (
  `forecast_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `required_employee_count` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`forecast_id`, `role_id`),
  INDEX `idx_staffing_requirement_role` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_staffing_requirement_forecast`
    FOREIGN KEY (`forecast_id`)
    REFERENCES `gastrosoft_course`.`workload_forecast` (`forecast_id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_staffing_requirement_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `gastrosoft_course`.`employee_role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
